// GENERATED by tools/tabler-icons/gen_tabler_icons.py from tools/tabler-icons/icons.txt. Do not edit.
package app.outgo.data.icon

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import app.outgo.R

/**
 * Category icons from Tabler Icons 3.48.0 (outline, MIT), shipped as VectorDrawables.
 * Their `icon.asset_key` is "tabler_<name>"; the bundled PNGs' keys never start with it.
 * The drawables are referenced here directly, so resource shrinking keeps them.
 */
object TablerIcons {
    const val KEY_PREFIX = "tabler_"

    /** A titled section of the category icon picker. */
    class Group(@StringRes val title: Int, val keys: List<String>)

    val GROUPS: List<Group> = listOf(
        Group(R.string.icon_group_food, listOf("tabler_soup", "tabler_bowl_chopsticks", "tabler_bowl_spoon", "tabler_salad", "tabler_sausage", "tabler_cheese", "tabler_candy", "tabler_lollipop", "tabler_apple", "tabler_cherry", "tabler_grape", "tabler_mushroom", "tabler_pepper", "tabler_milkshake", "tabler_bottle", "tabler_chef_hat", "tabler_tools_kitchen_2")),
        Group(R.string.icon_group_transport, listOf("tabler_car_suv", "tabler_truck", "tabler_truck_delivery", "tabler_parking", "tabler_car_garage", "tabler_car_crash", "tabler_steering_wheel", "tabler_road", "tabler_charging_pile", "tabler_engine", "tabler_bus_stop", "tabler_ship", "tabler_sailboat", "tabler_scooter_electric", "tabler_route")),
        Group(R.string.icon_group_shopping, listOf("tabler_basket", "tabler_tag", "tabler_discount", "tabler_gift_card", "tabler_hanger", "tabler_jacket", "tabler_eyeglass", "tabler_diamond", "tabler_device_desktop", "tabler_device_watch", "tabler_camera", "tabler_package", "tabler_perfume")),
        Group(R.string.icon_group_home, listOf("tabler_building", "tabler_building_community", "tabler_key", "tabler_lock", "tabler_bed", "tabler_plug", "tabler_router", "tabler_air_conditioning", "tabler_fridge", "tabler_microwave", "tabler_hammer", "tabler_paint", "tabler_bucket", "tabler_trash", "tabler_recycle", "tabler_file_invoice", "tabler_garden_cart")),
        Group(R.string.icon_group_education, listOf("tabler_certificate", "tabler_pencil", "tabler_notebook", "tabler_calculator", "tabler_language", "tabler_microscope", "tabler_flask", "tabler_palette", "tabler_presentation", "tabler_abacus", "tabler_backpack")),
        Group(R.string.icon_group_entertainment, listOf("tabler_microphone_2", "tabler_piano", "tabler_balloon", "tabler_cards", "tabler_dice", "tabler_chess", "tabler_puzzle", "tabler_photo", "tabler_masks_theater", "tabler_player_play", "tabler_ball_tennis", "tabler_ball_volleyball", "tabler_ball_bowling", "tabler_golf", "tabler_run", "tabler_yoga", "tabler_karate", "tabler_trekking", "tabler_fish_hook", "tabler_kayak")),
        Group(R.string.icon_group_health, listOf("tabler_stethoscope", "tabler_vaccine", "tabler_first_aid_kit", "tabler_eye", "tabler_bandage", "tabler_thermometer", "tabler_wheelchair", "tabler_massage", "tabler_brain", "tabler_zzz", "tabler_dna")),
        Group(R.string.icon_group_family, listOf("tabler_baby_bottle", "tabler_mood_kid", "tabler_horse_toy", "tabler_bone", "tabler_fish_bone", "tabler_heart", "tabler_man", "tabler_woman", "tabler_friends")),
        Group(R.string.icon_group_travel, listOf("tabler_beach", "tabler_mountain", "tabler_map", "tabler_world", "tabler_id", "tabler_building_skyscraper", "tabler_hotel_service", "tabler_caravan", "tabler_compass", "tabler_sunset", "tabler_building_castle", "tabler_torii", "tabler_building_arch")),
        Group(R.string.icon_group_finance, listOf("tabler_cash", "tabler_cash_banknote", "tabler_coins", "tabler_moneybag", "tabler_report_money", "tabler_chart_pie", "tabler_chart_candle", "tabler_currency_bitcoin", "tabler_currency_dong", "tabler_businessplan", "tabler_award", "tabler_trophy", "tabler_receipt_refund", "tabler_cash_register", "tabler_home_dollar", "tabler_shield_dollar")),
        Group(R.string.icon_group_other, listOf("tabler_printer", "tabler_mail", "tabler_cloud", "tabler_calendar", "tabler_clock", "tabler_scale")),
    )

    @DrawableRes
    fun drawable(assetKey: String): Int? = when (assetKey) {
        "tabler_soup" -> R.drawable.ic_cat_tabler_soup
        "tabler_bowl_chopsticks" -> R.drawable.ic_cat_tabler_bowl_chopsticks
        "tabler_bowl_spoon" -> R.drawable.ic_cat_tabler_bowl_spoon
        "tabler_salad" -> R.drawable.ic_cat_tabler_salad
        "tabler_sausage" -> R.drawable.ic_cat_tabler_sausage
        "tabler_cheese" -> R.drawable.ic_cat_tabler_cheese
        "tabler_candy" -> R.drawable.ic_cat_tabler_candy
        "tabler_lollipop" -> R.drawable.ic_cat_tabler_lollipop
        "tabler_apple" -> R.drawable.ic_cat_tabler_apple
        "tabler_cherry" -> R.drawable.ic_cat_tabler_cherry
        "tabler_grape" -> R.drawable.ic_cat_tabler_grape
        "tabler_mushroom" -> R.drawable.ic_cat_tabler_mushroom
        "tabler_pepper" -> R.drawable.ic_cat_tabler_pepper
        "tabler_milkshake" -> R.drawable.ic_cat_tabler_milkshake
        "tabler_bottle" -> R.drawable.ic_cat_tabler_bottle
        "tabler_chef_hat" -> R.drawable.ic_cat_tabler_chef_hat
        "tabler_tools_kitchen_2" -> R.drawable.ic_cat_tabler_tools_kitchen_2
        "tabler_car_suv" -> R.drawable.ic_cat_tabler_car_suv
        "tabler_truck" -> R.drawable.ic_cat_tabler_truck
        "tabler_truck_delivery" -> R.drawable.ic_cat_tabler_truck_delivery
        "tabler_parking" -> R.drawable.ic_cat_tabler_parking
        "tabler_car_garage" -> R.drawable.ic_cat_tabler_car_garage
        "tabler_car_crash" -> R.drawable.ic_cat_tabler_car_crash
        "tabler_steering_wheel" -> R.drawable.ic_cat_tabler_steering_wheel
        "tabler_road" -> R.drawable.ic_cat_tabler_road
        "tabler_charging_pile" -> R.drawable.ic_cat_tabler_charging_pile
        "tabler_engine" -> R.drawable.ic_cat_tabler_engine
        "tabler_bus_stop" -> R.drawable.ic_cat_tabler_bus_stop
        "tabler_ship" -> R.drawable.ic_cat_tabler_ship
        "tabler_sailboat" -> R.drawable.ic_cat_tabler_sailboat
        "tabler_scooter_electric" -> R.drawable.ic_cat_tabler_scooter_electric
        "tabler_route" -> R.drawable.ic_cat_tabler_route
        "tabler_basket" -> R.drawable.ic_cat_tabler_basket
        "tabler_tag" -> R.drawable.ic_cat_tabler_tag
        "tabler_discount" -> R.drawable.ic_cat_tabler_discount
        "tabler_gift_card" -> R.drawable.ic_cat_tabler_gift_card
        "tabler_hanger" -> R.drawable.ic_cat_tabler_hanger
        "tabler_jacket" -> R.drawable.ic_cat_tabler_jacket
        "tabler_eyeglass" -> R.drawable.ic_cat_tabler_eyeglass
        "tabler_diamond" -> R.drawable.ic_cat_tabler_diamond
        "tabler_device_desktop" -> R.drawable.ic_cat_tabler_device_desktop
        "tabler_device_watch" -> R.drawable.ic_cat_tabler_device_watch
        "tabler_camera" -> R.drawable.ic_cat_tabler_camera
        "tabler_package" -> R.drawable.ic_cat_tabler_package
        "tabler_perfume" -> R.drawable.ic_cat_tabler_perfume
        "tabler_building" -> R.drawable.ic_cat_tabler_building
        "tabler_building_community" -> R.drawable.ic_cat_tabler_building_community
        "tabler_key" -> R.drawable.ic_cat_tabler_key
        "tabler_lock" -> R.drawable.ic_cat_tabler_lock
        "tabler_bed" -> R.drawable.ic_cat_tabler_bed
        "tabler_plug" -> R.drawable.ic_cat_tabler_plug
        "tabler_router" -> R.drawable.ic_cat_tabler_router
        "tabler_air_conditioning" -> R.drawable.ic_cat_tabler_air_conditioning
        "tabler_fridge" -> R.drawable.ic_cat_tabler_fridge
        "tabler_microwave" -> R.drawable.ic_cat_tabler_microwave
        "tabler_hammer" -> R.drawable.ic_cat_tabler_hammer
        "tabler_paint" -> R.drawable.ic_cat_tabler_paint
        "tabler_bucket" -> R.drawable.ic_cat_tabler_bucket
        "tabler_trash" -> R.drawable.ic_cat_tabler_trash
        "tabler_recycle" -> R.drawable.ic_cat_tabler_recycle
        "tabler_file_invoice" -> R.drawable.ic_cat_tabler_file_invoice
        "tabler_garden_cart" -> R.drawable.ic_cat_tabler_garden_cart
        "tabler_certificate" -> R.drawable.ic_cat_tabler_certificate
        "tabler_pencil" -> R.drawable.ic_cat_tabler_pencil
        "tabler_notebook" -> R.drawable.ic_cat_tabler_notebook
        "tabler_calculator" -> R.drawable.ic_cat_tabler_calculator
        "tabler_language" -> R.drawable.ic_cat_tabler_language
        "tabler_microscope" -> R.drawable.ic_cat_tabler_microscope
        "tabler_flask" -> R.drawable.ic_cat_tabler_flask
        "tabler_palette" -> R.drawable.ic_cat_tabler_palette
        "tabler_presentation" -> R.drawable.ic_cat_tabler_presentation
        "tabler_abacus" -> R.drawable.ic_cat_tabler_abacus
        "tabler_backpack" -> R.drawable.ic_cat_tabler_backpack
        "tabler_microphone_2" -> R.drawable.ic_cat_tabler_microphone_2
        "tabler_piano" -> R.drawable.ic_cat_tabler_piano
        "tabler_balloon" -> R.drawable.ic_cat_tabler_balloon
        "tabler_cards" -> R.drawable.ic_cat_tabler_cards
        "tabler_dice" -> R.drawable.ic_cat_tabler_dice
        "tabler_chess" -> R.drawable.ic_cat_tabler_chess
        "tabler_puzzle" -> R.drawable.ic_cat_tabler_puzzle
        "tabler_photo" -> R.drawable.ic_cat_tabler_photo
        "tabler_masks_theater" -> R.drawable.ic_cat_tabler_masks_theater
        "tabler_player_play" -> R.drawable.ic_cat_tabler_player_play
        "tabler_ball_tennis" -> R.drawable.ic_cat_tabler_ball_tennis
        "tabler_ball_volleyball" -> R.drawable.ic_cat_tabler_ball_volleyball
        "tabler_ball_bowling" -> R.drawable.ic_cat_tabler_ball_bowling
        "tabler_golf" -> R.drawable.ic_cat_tabler_golf
        "tabler_run" -> R.drawable.ic_cat_tabler_run
        "tabler_yoga" -> R.drawable.ic_cat_tabler_yoga
        "tabler_karate" -> R.drawable.ic_cat_tabler_karate
        "tabler_trekking" -> R.drawable.ic_cat_tabler_trekking
        "tabler_fish_hook" -> R.drawable.ic_cat_tabler_fish_hook
        "tabler_kayak" -> R.drawable.ic_cat_tabler_kayak
        "tabler_stethoscope" -> R.drawable.ic_cat_tabler_stethoscope
        "tabler_vaccine" -> R.drawable.ic_cat_tabler_vaccine
        "tabler_first_aid_kit" -> R.drawable.ic_cat_tabler_first_aid_kit
        "tabler_eye" -> R.drawable.ic_cat_tabler_eye
        "tabler_bandage" -> R.drawable.ic_cat_tabler_bandage
        "tabler_thermometer" -> R.drawable.ic_cat_tabler_thermometer
        "tabler_wheelchair" -> R.drawable.ic_cat_tabler_wheelchair
        "tabler_massage" -> R.drawable.ic_cat_tabler_massage
        "tabler_brain" -> R.drawable.ic_cat_tabler_brain
        "tabler_zzz" -> R.drawable.ic_cat_tabler_zzz
        "tabler_dna" -> R.drawable.ic_cat_tabler_dna
        "tabler_baby_bottle" -> R.drawable.ic_cat_tabler_baby_bottle
        "tabler_mood_kid" -> R.drawable.ic_cat_tabler_mood_kid
        "tabler_horse_toy" -> R.drawable.ic_cat_tabler_horse_toy
        "tabler_bone" -> R.drawable.ic_cat_tabler_bone
        "tabler_fish_bone" -> R.drawable.ic_cat_tabler_fish_bone
        "tabler_heart" -> R.drawable.ic_cat_tabler_heart
        "tabler_man" -> R.drawable.ic_cat_tabler_man
        "tabler_woman" -> R.drawable.ic_cat_tabler_woman
        "tabler_friends" -> R.drawable.ic_cat_tabler_friends
        "tabler_beach" -> R.drawable.ic_cat_tabler_beach
        "tabler_mountain" -> R.drawable.ic_cat_tabler_mountain
        "tabler_map" -> R.drawable.ic_cat_tabler_map
        "tabler_world" -> R.drawable.ic_cat_tabler_world
        "tabler_id" -> R.drawable.ic_cat_tabler_id
        "tabler_building_skyscraper" -> R.drawable.ic_cat_tabler_building_skyscraper
        "tabler_hotel_service" -> R.drawable.ic_cat_tabler_hotel_service
        "tabler_caravan" -> R.drawable.ic_cat_tabler_caravan
        "tabler_compass" -> R.drawable.ic_cat_tabler_compass
        "tabler_sunset" -> R.drawable.ic_cat_tabler_sunset
        "tabler_building_castle" -> R.drawable.ic_cat_tabler_building_castle
        "tabler_torii" -> R.drawable.ic_cat_tabler_torii
        "tabler_building_arch" -> R.drawable.ic_cat_tabler_building_arch
        "tabler_cash" -> R.drawable.ic_cat_tabler_cash
        "tabler_cash_banknote" -> R.drawable.ic_cat_tabler_cash_banknote
        "tabler_coins" -> R.drawable.ic_cat_tabler_coins
        "tabler_moneybag" -> R.drawable.ic_cat_tabler_moneybag
        "tabler_report_money" -> R.drawable.ic_cat_tabler_report_money
        "tabler_chart_pie" -> R.drawable.ic_cat_tabler_chart_pie
        "tabler_chart_candle" -> R.drawable.ic_cat_tabler_chart_candle
        "tabler_currency_bitcoin" -> R.drawable.ic_cat_tabler_currency_bitcoin
        "tabler_currency_dong" -> R.drawable.ic_cat_tabler_currency_dong
        "tabler_businessplan" -> R.drawable.ic_cat_tabler_businessplan
        "tabler_award" -> R.drawable.ic_cat_tabler_award
        "tabler_trophy" -> R.drawable.ic_cat_tabler_trophy
        "tabler_receipt_refund" -> R.drawable.ic_cat_tabler_receipt_refund
        "tabler_cash_register" -> R.drawable.ic_cat_tabler_cash_register
        "tabler_home_dollar" -> R.drawable.ic_cat_tabler_home_dollar
        "tabler_shield_dollar" -> R.drawable.ic_cat_tabler_shield_dollar
        "tabler_printer" -> R.drawable.ic_cat_tabler_printer
        "tabler_mail" -> R.drawable.ic_cat_tabler_mail
        "tabler_cloud" -> R.drawable.ic_cat_tabler_cloud
        "tabler_calendar" -> R.drawable.ic_cat_tabler_calendar
        "tabler_clock" -> R.drawable.ic_cat_tabler_clock
        "tabler_scale" -> R.drawable.ic_cat_tabler_scale
        else -> null
    }
}
